on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout_Repo
      uses: actions/checkout@v2
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: jdposa/hugo_backend
        options: -v ${{ github.workspace }}:/home
        run: |        
          cd /home \
          && git config user.name github-actions \
          && git config user.email github-actions@github.com \
          && git fetch \ 
          && git branch
